-  derived_data_file:
   - Derived Spectral Data File
   - Metabolite Assignment File
   key_file_prefix: nmr_raw
   measurement_type:
      term: metabolite profiling
      url: http://purl.obolibrary.org/obo/OBI_0000366
   node_name: NMR Assay Name
   parameter-like_file:
      value: Acquisition Parameter File
   protocol_type:
      term: NMR spectroscopy
      url: http://purl.obolibrary.org/obo/OBI_0000623
   raw_data_file: Free Induction Decay Data File
   technology_type:
      term: NMR spectroscopy
      url: http://purl.obolibrary.org/obo/OBI_0000623
-  derived_data_file:
   - Derived Spectral Data File
   - Metabolite Assignment File
   key_file_prefix: nmr_raw
   measurement_type:
      term: targeted metabolite profiling
      url: http://purl.obolibrary.org/obo/MSIO_0000100
   node_name: NMR Assay Name
   parameter-like_file:
      value: ''
   protocol_type:
      term: NMR spectroscopy
      url: http://purl.obolibrary.org/obo/OBI_0000623
   raw_data_file: Free Induction Decay Data File
   technology_type:
      term: NMR spectroscopy
      url: http://purl.obolibrary.org/obo/OBI_0000623
-  derived_data_file:
   - Derived Spectral Data File
   - Metabolite Assignment File
   key_file_prefix: nmr_raw
   measurement_type:
      term: untargeted metabolite profiling
      url: http://purl.obolibrary.org/obo/MSIO_0000101
   node_name: NMR Assay Name
   parameter-like_file:
      value: ''
   protocol_type:
      term: NMR spectroscopy
      url: http://purl.obolibrary.org/obo/OBI_0000623
   raw_data_file: Free Induction Decay Data File
   technology_type:
      term: NMR spectroscopy
      url: http://purl.obolibrary.org/obo/OBI_0000623
-  derived_data_file:
   - Derived Spectral Data File
   - Metabolite Assignment File
   key_file_prefix: nmr_raw
   measurement_type:
      term: isotopomer distribution analysis
      url: http://purl.obolibrary.org/obo/msio.owl#isotopomer_analysis
   node_name: NMR Assay Name
   parameter-like_file:
      value: ''
   protocol_type:
      term: NMR spectroscopy
      url: http://purl.obolibrary.org/obo/OBI_0000623
   raw_data_file: Free Induction Decay Data File
   technology_type:
      term: NMR spectroscopy
      url: http://purl.obolibrary.org/obo/OBI_0000623
-  derived_data_file:
   - Derived Spectral Data File
   - Metabolite Assignment File
   key_file_prefix: ms_raw
   measurement_type:
      term: metabolite profiling
      url: http://purl.obolibrary.org/obo/OBI_0000366
   node_name: MS Assay Name
   parameter-like_file:
      value: ''
   protocol_type:
      term: mass spectrometry
      url: http://purl.obolibrary.org/obo/OBI_0000470
   raw_data_file: Raw Spectral Data File
   technology_type:
      term: mass spectrometry
      url: http://purl.obolibrary.org/obo/OBI_0000470
-  derived_data_file:
   - Derived Spectral Data File
   - Metabolite Assignment File
   key_file_prefix: ms_raw
   measurement_type:
      term: targeted metabolite profiling
      url: http://purl.obolibrary.org/obo/MSIO_0000100
   node_name: MS Assay Name
   parameter-like_file:
      value: ''
   protocol_type:
      term: mass spectrometry
      url: http://purl.obolibrary.org/obo/OBI_0000470
   raw_data_file: Raw Spectral Data File
   technology_type:
      term: mass spectrometry
      url: http://purl.obolibrary.org/obo/OBI_0000470
-  derived_data_file:
   - Derived Spectral Data File
   - Metabolite Assignment File
   key_file_prefix: ms_raw
   measurement_type:
      term: untargeted metabolite profiling
      url: http://purl.obolibrary.org/obo/MSIO_0000101
   node_name: MS Assay Name
   parameter-like_file:
      value: ''
   protocol_type:
      term: mass spectrometry
      url: http://purl.obolibrary.org/obo/OBI_0000470
   raw_data_file: Raw Spectral Data File
   technology_type:
      term: mass spectrometry
      url: http://purl.obolibrary.org/obo/OBI_0000470
-  derived_data_file:
   - Derived Spectral Data File
   key_file_prefix: ms_raw
   measurement_type:
      term: isotologue distribution analysis
      url: http://purl.obolibrary.org/obo/msio.owl#mass_isotopologue_distribution_analysis
   node_name: MS Assay Name
   parameter-like_file:
      value: ''
   protocol_type:
      term: mass spectrometry
      url: http://purl.obolibrary.org/obo/OBI_0000470
   raw_data_file: Raw Spectral Data File
   technology_type:
      term: mass spectrometry
      url: http://purl.obolibrary.org/obo/OBI_0000470
-  derived_data_file:
   - Derived Array Data File
   key_file_prefix: array_raw
   measurement_type:
      term: transcription profiling
      url: http://purl.obolibrary.org/obo/OBI_0000424
   node_name: Hybridization Assay Name
   parameter-like_file:
      value: Array Design REF
   protocol_type:
      term: nucleic acid hybridization
      url: http://purl.obolibrary.org/obo/OBI_0302903
   raw_data_file: Raw Data File
   technology_type:
      term: DNA microarray
      url: http://purl.obolibrary.org/obo/OBI_0400148
-  derived_data_file:
   - Derived Array Data File
   key_file_prefix: array_raw
   measurement_type:
      term: genotype profiling
      url: http://purl.obolibrary.org/obo/OBI_0000435
   node_name: Hybridization Assay Name
   parameter-like_file:
      value: Array Design REF
   protocol_type:
      term: nucleic acid hybridization
      url: http://purl.obolibrary.org/obo/OBI_0302903
   raw_data_file: Raw Data File
   technology_type:
      term: DNA microarray
      url: http://purl.obolibrary.org/obo/OBI_0000253
-  derived_data_file:
   - Derived Array Data File
   key_file_prefix: array_raw
   measurement_type:
      term: epigenome profling
      url: http://purl.obolibrary.org/obo/OBI_0002020
   node_name: Hybridization Assay Name
   parameter-like_file:
      value: Array Design REF
   protocol_type:
      term: nucleic acid hybridization
      url: http://purl.obolibrary.org/obo/OBI_0302903
   raw_data_file: Raw Data File
   technology_type:
      term: DNA microarray
      url: http://purl.obolibrary.org/obo/OBI_0400148
-  derived_data_file:
   - Derived Array Data File
   key_file_prefix: array_raw
   measurement_type:
      term: exome profiling
      url: http://purl.obolibrary.org/obo/OBI_0002118
   node_name: Hybridization Assay Name
   parameter-like_file:
      value: Array Design REF
   protocol_type:
      term: nucleic acid hybridization
      url: http://purl.obolibrary.org/obo/OBI_0302903
   raw_data_file: Raw Data File
   technology_type:
      term: DNA microarray
      url: http://purl.obolibrary.org/obo/OBI_0400148
-  derived_data_file:
   - Derived Array Data File
   key_file_prefix: array_raw
   measurement_type:
      term: DNA methylation profiling
      url: http://purl.obolibrary.org/obo/OBI_0000634
   node_name: Hybridization Assay Name
   parameter-like_file:
      value: Array Design REF
   protocol_type:
      term: nucleic acid hybridization
      url: http://purl.obolibrary.org/obo/OBI_0302903
   raw_data_file: Raw Data File
   technology_type:
      term: DNA microarray
      url: http://purl.obolibrary.org/obo/OBI_0400148
-  derived_data_file:
   - Derived Array Data File
   key_file_prefix: array_raw
   measurement_type:
      term: copy number variation profling
      url: http://purl.obolibrary.org/obo/OBI_0000537
   node_name: Hybridization Assay Name
   parameter-like_file:
      value: Array Design REF
   protocol_type:
      term: nucleic acid hybridization
      url: http://purl.obolibrary.org/obo/OBI_0302903
   raw_data_file: Raw Data File
   technology_type:
      term: DNA microarray
      url: http://purl.obolibrary.org/obo/OBI_0400148
-  derived_data_file:
   - Derived Array Data File
   key_file_prefix: array_raw
   measurement_type:
      term: transcription factor binding site identification
      url: http://purl.obolibrary.org/obo/OBI_0000291
   node_name: Hybridization Assay Name
   parameter-like_file:
      value: Array Design REF
   protocol_type:
      term: nucleic acid hybridization
      url: http://purl.obolibrary.org/obo/OBI_0302903
   raw_data_file: Raw Data File
   technology_type:
      term: DNA microarray
      url: http://purl.obolibrary.org/obo/OBI_0400148
-  derived_data_file:
   - Derived Array Data File
   key_file_prefix: array_raw
   measurement_type:
      term: protein-DNA binding site identification
      url: http://www.bioassayontology.org/bao#BAO_0000591
   node_name: Hybridization Assay Name
   parameter-like_file:
      value: Array Design REF
   protocol_type:
      term: nucleic acid hybridization
      url: http://purl.obolibrary.org/obo/OBI_0302903
   raw_data_file: Raw Data File
   technology_type:
      term: DNA microarray
      url: http://purl.obolibrary.org/obo/OBI_0400148
-  derived_data_file:
   - Derived Array Data File
   key_file_prefix: array_raw
   measurement_type:
      term: SNP analysis
      url: http://purl.obolibrary.org/obo/OBI_0000435
   node_name: Hybridization Assay Name
   parameter-like_file:
      value: Array Design REF
   protocol_type:
      term: nucleic acid hybridization
      url: http://purl.obolibrary.org/obo/OBI_0302903
   raw_data_file: Raw Data File
   technology_type:
      term: DNA microarray
      url: http://purl.obolibrary.org/obo/OBI_0400148
-  derived_data_file:
   - Derived Data File
   key_file_prefix: raw
   measurement_type:
      term: transcription profiling
      url: http://purl.obolibrary.org/obo/OBI_0000424
   node_name: Assay Name
   parameter-like_file:
      value: ''
   protocol_type:
      term: nucleic acid sequencing
      url: http://purl.obolibrary.org/obo/OBI_0600047
   raw_data_file: 'Raw Data File '
   technology_type:
      term: nucleic acid sequencing
      url: http://purl.obolibrary.org/obo/OBI_0600047
-  derived_data_file:
   - Derived Data File
   key_file_prefix: raw
   measurement_type:
      term: transcription factor binding site identification
      url: http://purl.obolibrary.org/obo/OBI_0000291
   node_name: Assay Name
   parameter-like_file:
      value: ''
   protocol_type:
      term: nucleic acid sequencing
      url: http://purl.obolibrary.org/obo/OBI_0600047
   raw_data_file: 'Raw Data File '
   technology_type:
      term: nucleic acid sequencing
      url: http://purl.obolibrary.org/obo/OBI_0600047
-  derived_data_file:
   - Derived Data File
   key_file_prefix: raw
   measurement_type:
      term: protein-DNA binding site identification
      url: http://www.bioassayontology.org/bao#BAO_0000591
   node_name: Assay Name
   parameter-like_file:
      value: ''
   protocol_type:
      term: nucleic acid sequencing
      url: http://purl.obolibrary.org/obo/OBI_0600047
   raw_data_file: 'Raw Data File '
   technology_type:
      term: nucleic acid sequencing
      url: http://purl.obolibrary.org/obo/OBI_0600047
-  derived_data_file:
   - Derived Data File
   key_file_prefix: raw
   measurement_type:
      term: DNA methylation profiling
      url: http://purl.obolibrary.org/obo/OBI_0000634
   node_name: Assay Name
   parameter-like_file:
      value: ''
   protocol_type:
      term: nucleic acid sequencing
      url: http://purl.obolibrary.org/obo/OBI_0600047
   raw_data_file: 'Raw Data File '
   technology_type:
      term: nucleic acid sequencing
      url: http://purl.obolibrary.org/obo/OBI_0600047
-  derived_data_file:
   - Derived Data File
   key_file_prefix: raw
   measurement_type:
      term: histone modification profiling
      url: http://purl.obolibrary.org/obo/OBI_0002020
   node_name: Assay Name
   parameter-like_file:
      value: ''
   protocol_type:
      term: nucleic acid sequencing
      url: http://purl.obolibrary.org/obo/OBI_0600047
   raw_data_file: 'Raw Data File '
   technology_type:
      term: nucleic acid sequencing
      url: http://purl.obolibrary.org/obo/OBI_0600047
-  derived_data_file:
   - Derived Data File
   key_file_prefix: raw
   measurement_type:
      term: genome sequencing
      url: http://purl.obolibrary.org/obo/OBI_0002117
   node_name: Assay Name
   parameter-like_file:
      value: ''
   protocol_type:
      term: nucleic acid sequencing
      url: http://purl.obolibrary.org/obo/OBI_0600047
   raw_data_file: 'Raw Data File '
   technology_type:
      term: nucleic acid sequencing
      url: http://purl.obolibrary.org/obo/OBI_0600047
-  derived_data_file:
   - Derived Data File
   key_file_prefix: raw
   measurement_type:
      term: metagenome sequencing
      url: http://purl.obolibrary.org/obo/OBI_0002623
   node_name: Assay Name
   parameter-like_file:
      value: ''
   protocol_type:
      term: nucleic acid sequencing
      url: http://purl.obolibrary.org/obo/OBI_0600047
   raw_data_file: 'Raw Data File '
   technology_type:
      term: nucleic acid sequencing
      url: http://purl.obolibrary.org/obo/OBI_0600047
-  derived_data_file:
   - Derived Data File
   key_file_prefix: raw
   measurement_type:
      term: environmental gene survey
      url: http://purl.obolibrary.org/obo/OBI_0001960
   node_name: Assay Name
   parameter-like_file:
      value: ''
   protocol_type:
      term: nucleic acid sequencing
      url: http://purl.obolibrary.org/obo/OBI_0600047
   raw_data_file: 'Raw Data File '
   technology_type:
      term: nucleic acid sequencing
      url: http://purl.obolibrary.org/obo/OBI_0600047
-  derived_data_file:
   - Derived Data File
   key_file_prefix: raw
   measurement_type:
      term: cell sorting
      url: http://purl.obolibrary.org/obo/CHMO_0001085
   node_name: Assay Name
   parameter-like_file:
      value: ''
   protocol_type:
      term: flow cytometry
      url: http://purl.obolibrary.org/obo/OBI_0000916
   raw_data_file: 'Raw Data File '
   technology_type:
      term: flow cytometry
      url: http://purl.obolibrary.org/obo/OBI_0000916
-  derived_data_file:
   - Derived Data File
   key_file_prefix: raw
   measurement_type:
      term: cell counting
      url: http://purl.obolibrary.org/obo/OBI_0001977
   node_name: Assay Name
   parameter-like_file:
      value: ''
   protocol_type:
      term: flow cytometry
      url: http://purl.obolibrary.org/obo/OBI_0000916
   raw_data_file: 'Raw Data File '
   technology_type:
      term: flow cytometry
      url: http://purl.obolibrary.org/obo/OBI_0000916
-  derived_data_file:
   - Derived Data File
   key_file_prefix: raw
   measurement_type:
      term: cell migration assay
      url: ''
   node_name: Assay Name
   parameter-like_file:
      value: ''
   protocol_type:
      term: migration assay
      url: http://purl.obolibrary.org/obo/OBI_0002119
   raw_data_file: Raw Data File
   technology_type:
      term: microscopy imaging
      url: http://purl.obolibrary.org/obo/OBI_0002119
-  derived_data_file:
   - Derived Data File
   key_file_prefix: raw
   measurement_type:
      term: phenotyping
      url: ''
   node_name: Assay Name
   parameter-like_file:
      value: ''
   protocol_type:
      term: migration assay
      url: http://purl.obolibrary.org/obo/OBI_0000185
   raw_data_file: Raw Data File
   technology_type:
      term: imaging
      url: http://purl.obolibrary.org/obo/OBI_0000185
-  derived_data_file:
   - Derived Data File
   key_file_prefix: raw
   measurement_type:
      term: transcription profiling
      url: http://purl.obolibrary.org/obo/OBI_0000424
   node_name: Assay Name
   parameter-like_file:
      value: ''
   protocol_type:
      term: RT-pcr
      url: http://purl.obolibrary.org/obo/OBI_0001361
   raw_data_file: 'Raw Data File '
   technology_type:
      term: RT-pcr
      url: http://purl.obolibrary.org/obo/OBI_0001361
-  derived_data_file:
   - Derived Data File
   key_file_prefix: custom_raw
   measurement_type:
      term: custom assay
      url: ''
   node_name: Assay Name
   parameter-like_file:
      value: ''
   protocol_type:
      term: custom prococol
      url: ''
   raw_data_file: 'Raw Data File '
   technology_type:
      term: custom technique
      url: ''
-  derived_data_file:
   - Derived Spectral Data File
   - Peptide Assignment File
   - Protein Assignment File
   - Post Translational Modification Assignment File
   key_file_prefix: ms_raw
   measurement_type:
      term: protein expression profiling
      url: http://purl.obolibrary.org/obo/OBI_0000615
   node_name: MS Assay Name
   parameter-like_file:
      value: ''
   protocol_type:
      term: mass spectrometry
      url: http://purl.obolibrary.org/obo/OBI_0000470
   raw_data_file: Raw Spectral Data File
   technology_type:
      term: mass spectrometry
      url: http://purl.obolibrary.org/obo/OBI_0000470
